Booking System/Models/configuration.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuration
    {
        public int configuration_id { get; set; }
        public string conf_key { get; set; }
        public string conf_type { get; set; }
        public string conf_value { get; set; }
        public bool system_based { get; set; }
    }
}

Booking System/Models/feature.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public feature()
        {
            this.room_feature = new HashSet<roomFeature>();
            this.hotel_feature = new HashSet<hotelFeature>();
            this.vehicle_feature = new HashSet<vehicleFeature>();
        }
    
        public int feature_id { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public string feature_type { get; set; }
        public string name { get; set; }
        public string icon { get; set; }
        public bool is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roomFeature> room_feature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hotelFeature> hotel_feature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicleFeature> vehicle_feature { get; set; }
    }
}

Booking System/Models/mealPlan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mealPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mealPlan()
        {
            this.supplements = new HashSet<supplement>();
            this.base_price = new HashSet<basePrice>();
        }
    
        public int meal_plan_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<short> meal_order { get; set; }
        public string code { get; set; }
        public bool is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplement> supplements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<basePrice> base_price { get; set; }
    }
}

Booking System/Controllers/SystemSettingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Booking_System.Models;
using System.Data.Entity.Infrastructure;
using Booking_System.Helpers;
using System.Web.Script.Serialization;
using System.IO;
using System.Text;

namespace Booking_System.Controllers
{
    public class SystemSettingsController : AdminController
    {
        private ABSDBEntities db = new ABSDBEntities();

        public ActionResult Icons()
        {
            
            return View();
        }

        #region "Hotel & Room Features"
        public ActionResult Features(string id = "H")
        {
            ViewBag.FeatureType = id;
            return View(db.features.Where(x => x.feature_type == id).ToList());
        }


        // GET: Features/Create
        public ActionResult CreateFeature(string id)
        {
            ViewBag.FeatureType = id;
            return View();
        }

        // POST: Features/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFeature([Bind(Include = "feature_id,category,description,feature_type,name,icon")] feature feature)
        {
            if (ModelState.IsValid)
            {

                feature.is_active = true;
                db.features.Add(feature);
                db.SaveChanges();
                SaveAudit(AppEnums.Event.CREATE, "Feature", feature.feature_id);


                return RedirectToAction("Features", new { id = feature.feature_type });
            }

            return View(feature);
        }

        // GET: Features/Edit/5
        public ActionResult EditFeature(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            feature feature = db.features.Find(id);
            if (feature == null)
            {
                return HttpNotFound();
            }
          
            return View(feature);
        }

        // POST: Features/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFeature([Bind(Include = "feature_id,category,description,feature_type,name,icon")] feature feature)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feature).State = EntityState.Modified;
                db.SaveChanges();
                SaveAudit(AppEnums.Event.UPDATE, "Feature", feature.feature_id);
                return RedirectToAction("Features", new { id = feature.feature_type });
            }
            return View(feature);
        }

        // GET: Features/Delete/5
        public ActionResult DeleteFeature(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            feature feature = db.features.Find(id);
            if (feature == null)
            {
                return HttpNotFound();
            }
            return View(feature);
        }

        // POST: Features/Delete/5
        [HttpPost, ActionName("DeleteFeature")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                feature feature = db.features.Find(id);
                var type = feature.feature_type;
                db.features.Remove(feature);
                db.SaveChanges();
                SaveAudit(AppEnums.Event.DELETE, "Feature", feature.feature_id);

                return RedirectToAction("Features", new { id = type });
            }
            catch (Exception)
            {

                throw;
            }
           
        }

        #endregion


        #region currency


        public ActionResult Currencies(bool ShowAll=false)
        {

            var currencies = db.currencies.ToList();
            if (!ShowAll)
                currencies = currencies.Where(x => x.is_active).ToList();

            ViewBag.ShowAll = ShowAll;
            return View(currencies);
        }

        public ActionResult CreateCurrency()
        {
                     
            return View();
        }


        [HttpPost]
        public ActionResult CreateCurrency([Bind(Include = "currency_code,currency_desc,symbol,exchange_rate")] currency currency)
        {

            try
            {

                var obj = db.currencies.Where(x => x.currency_code == currency.currency_code).Count();
                if (obj >0)
                {
                    ModelState.AddModelError("currency_code", "The currency code already exist");
                    return View(currency);
                }

                if (ModelState.IsValid)
                {
                    currency.is_active = true;  
                        db.currencies.Add(currency);
                        db.SaveChanges();
                            SaveAudit(AppEnums.Event.CREATE, "Currency", currency.currency_id);
                        return RedirectToAction("Currencies");
                    
                }
                return View(currency);
            }
            catch (Exception)
            {

                throw;
                
            }
           
        }


        public ActionResult EditCurrency(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                currency currency = db.currencies.Find(id);
                if (currency == null)
                {
                    return HttpNotFound();
                }


                return View(currency);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpGet]
        public ActionResult DisableCurrency(string id, string value)
        {
            try
            {
                var currency = db.currencies.Find(Int32.Parse(id));

                currency.is_active = (value == "1") ? true: false;
                db.Entry(currency).State = EntityState.Modified;
                db.SaveChanges();

                SaveAudit(AppEnums.Event.UPDATE, "Currency", currency.currency_id);
                return Json("ok", JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
               
                return Json(ex.InnerException, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult EditCurrency([Bind(Include = "currency_id,currency_code,currency_desc,symbol,exchange_rate,is_active")] currency currency)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(currency).State = EntityState.Modified;
                    db.SaveChanges();
                    SaveAudit(AppEnums.Event.UPDATE, "Currency", 0);
                    return RedirectToAction("Currencies");
                }
                return View(currency);
            }
            catch (Exception)
            {

                throw;
            }
            
        }

        [HttpPost, ActionName("DeleteCurrency")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCurrency([Bind(Include = "currency_id,currency_code,currency_desc,symbol")] currency currency)
        {
            try
            {
                var curr = db.currencies.Find(currency.currency_id);
                db.currencies.Remove(curr);
                db.SaveChanges();
                SaveAudit(AppEnums.Event.DELETE, "Currency", 0);
                return RedirectToAction("Currencies");
            }
            catch (Exception)
            {

                throw;
            }
        }

        // POST: currencies/Delete/5

        public ActionResult DeleteCurrency(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            currency currency = db.currencies.Find(id);
            if (currency == null)
            {
                return HttpNotFound();
            }

            return View(currency);
        }
        #endregion

        #region occupancies

        public ActionResult Occupancies()
        {
            return View(db.occupancies.ToList());
        }

        // GET: Occupancies/Create
        public ActionResult CreateOccupancy()
        {
            return View();
        }

        // POST: Occupancies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOccupancy([Bind(Include = "occupancy_id,name,description,infant,child,teen,adult,senior,without_bed")] occupancy occupancy)
        {

            bool HasValidationErrors = false;
            List<String> errors = new List<String>();
            if (occupancy.occupancyCode == 0)
            {
                HasValidationErrors = true;
                errors.Add("At least on occupancy needs to be more than 0");
            }

            var existingOccupancies = db.occupancies.ToList();

            if (existingOccupancies.Contains(occupancy))
            {
                HasValidationErrors = true;

Booking System/Views/SystemSettings/ConfigurationDetails.cshtml
@model Booking_System.Models.configuration

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>configuration</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.conf_key)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.conf_key)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.conf_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.conf_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.conf_value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.conf_value)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.configuration_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Booking System/Views/SystemSettings/CreateCurrency.cshtml
@model Booking_System.Models.currency

@{
    ViewBag.Title = "Create";

    ViewBag.TreeView = "S";
    ViewBag.Menu = "Currency";
}

<h2>Create Currency</h2>

<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li><a href="@Url.Action("Currencies")">Currencies</a></li>
    <li class="active">Create Currency</li>
</ol>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    if (!Html.ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            @Html.ValidationSummary()
        </div>
    }


        <div class="row">

            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><span class="badge">1</span>&nbsp;Features</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.currency_code, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.currency_code, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.currency_code, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.currency_desc, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.currency_desc, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.currency_desc, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.symbol, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.symbol, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.symbol, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.exchange_rate, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.exchange_rate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.exchange_rate, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <a href="@Url.Action("Currencies")" type="button" class="btn btn-default">Cancel</a>
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        @*<div class="box-footer">
            <button type="submit" class="btn btn-primary">Create</button>
        </div>*@

}
@section Scripts {
 
}

Booking System/Views/SystemSettings/DeleteConfiguration.cshtml
@model Booking_System.Models.configuration

@{
    ViewBag.Title = "Delete Configuration";

    ViewBag.TreeView = "S";
    ViewBag.Menu = "Configuration";
}


<h2><span class="fa fa-trash"></span> Delete Configuration</h2>

<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li><a href="@Url.Action("Configuration")">Configurations</a></li>
    <li class="active">Delete Configuration</li>
</ol>

<div class="row">

    <div class="col-md-offset-4 col-md-4">
        <div class="box box-danger">
            <div class="box-header with-border">
                <h3 class="box-title">Are you sure you want to <b>delete </b>this?</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.conf_key)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.conf_key)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.conf_type)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.conf_type)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.conf_value)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.conf_value)
                        </dd>

                    </dl>
                    <p class="text-center text-danger"><em>Note:</em> Once deleted item cannot be recovered.</p>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color text-center">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            <a href="@Url.Action("Configurations")" type="button" class="btn btn-default">Do not delete</a>

                        </div>
                    }
                </div>
            </div>  <!-- body-->
        </div>  <!-- box -->
    </div>  <!-- col -->
</div> <!-- row -->

Booking System/Views/SystemSettings/DeleteCurrency.cshtml
@model Booking_System.Models.currency

@{
    ViewBag.Title = "Delete";
}

<h2><span class="fa fa-trash"></span> Delete Currency</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>

    <li><a href="@Url.Action("Currencies", "SystemSettings")">Currencies</a></li>
    @*<li><a href="@Url.Action(_methodDetails, "SystemSettings", new { id = _id, tab = _tab })">@Model.provider.name</a></li>*@

    <li class="active">Delete Currency</li>
</ol>

<div class="col-md-offset-4 col-md-4">
    <div class="box box-danger">
        <div class="box-header with-border">
            <h3 class="box-title">Are you sure you want to <b>delete </b>this?</h3>
        </div><!-- /.box-header -->
        <div class="box-body">

            <div>
                <h4>currency</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.currency_code)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.currency_code)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.currency_desc)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.currency_desc)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.symbol)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.symbol)
                    </dd>
                </dl>
                <p class="text-center text-danger"><em>Note:</em> Once deleted item cannot be recovered.</p>


                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.currency_id)
                    <div class="form-actions no-color text-center">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        <a href="@Url.Action("Currencies", "SystemSettings")" type="button" class="btn btn-default">Do not delete</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
            

Booking System/Views/SystemSettings/MealPlanDetails.cshtml
@model Booking_System.Models.mealPlan

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>mealPlan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.meal_order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meal_order)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.code)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.meal_plan_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Booking System/Views/SystemSettings/MealPlans.cshtml
@model IEnumerable<Booking_System.Models.mealPlan>

@{
    ViewBag.Title = "Index";
    ViewBag.TreeView = "S";
    ViewBag.Menu = "MealPlan";
}



<h2>Meal Plans</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li class="active">Meal Plans</li>
</ol>

@*<p>
        <a href="@Url.Action("Create","Features", new {  id = ViewBag.FeatureType })"><span class="fa fa-plus"></span> New @hotelroom Feature</a>
    </p>*@

<div class="box">
    <div class="box-header box-danger ">
        <h3 class="box-title">Meal Plans</h3>
        <div class="box-tools">
            <a href="@Url.Action("CreateMealPlan","SystemSettings")"><span class="fa fa-plus-circle"></span> New Meal Plan</a>
        </div>

    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
   
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.meal_order)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.code)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.meal_order)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.code)
                    </td>
                    <td>
                        <a href="@Url.Action("EditMealPlan", new { id = item.meal_plan_id})" title="Edit Meal Plan"><span class="fa fa-pencil"></span></a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                        <a href="@Url.Action("DeleteMealPlan", new { id = item.meal_plan_id})" title="Delete Meal Plan"><span class="fa fa-trash"></span></a>
                    </td>
                </tr>
            }

        </table>


    </div> <!-- box body-->
</div> <!-- box -->

Booking System/Views/SystemSettings/Occupancies.cshtml
@model IEnumerable<Booking_System.Models.occupancy>

@{
    ViewBag.Title = "Occupancy";

    ViewBag.TreeView = "S";
    ViewBag.Menu = "Occupancy";

}


<h2>Occupancies</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li class="active">Room Occupancies</li>
</ol>

@*<p>
        <a href="@Url.Action("Create","Features", new {  id = ViewBag.FeatureType })"><span class="fa fa-plus"></span> New @hotelroom Feature</a>
    </p>*@

<div class="box">
    <div class="box-header box-danger ">
        <h3 class="box-title">Occupancies</h3>
        <div class="box-tools">
                <a href="@Url.Action("CreateOccupancy","SystemSettings")"><span class="fa fa-plus-circle"></span> New Occupancy</a>
        </div>

    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.description)
                </th>
                <th align="center">
                    @Html.DisplayNameFor(model => model.adult)
                </th>

                <th align="center">
                    @Html.DisplayNameFor(model => model.infant)
                </th>
                <th align="center">

                    @*@Html.DisplayNameFor(model => model.child)*@
                    No. Children
                    
                </th>
                @*<th align="center">


                    Child W/O Bed
                </th>*@
                <th align="center">

                    @Html.DisplayNameFor(model => model.teen)
                </th>
                
               
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>

                    <td align="center">
                        <span class="label label-@(item.adult>0?"success":"default")">

                            @Html.DisplayFor(modelItem => item.adult)
                        </span>
                    </td>
                    <td align="center">
                        <span class="label label-@(item.infant>0?"success":"default")">
                            @Html.DisplayFor(modelItem => item.infant)
                        </span>

</td>
                    <td align="center">
                        <span class="label label-@(item.child>0?"success":"default")">
                            @Html.DisplayFor(modelItem => item.child)
                        </span>

</td>
                    @*<td align="center">
                        <span class="label label-@(item.without_bed>0?"success":"default")">
                            @Html.DisplayFor(modelItem => item.without_bed)
                        </span>

</td>*@

                    <td align="center">
                        <span class="label label-@(item.teen>0?"success":"default")">
                            @Html.DisplayFor(modelItem => item.teen)
                        </span>

</td>
                    
                    <td>
                     @*   <a href="@Url.Action("Details", new { id = item.occupancy_id})" title="view Occupancy"><span class="fa fa-tv"></span></a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;*@
                        <a href="@Url.Action("EditOccupancy", new { id = item.occupancy_id})" title="Edit Occupancy"><span class="fa fa-pencil"></span></a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                        <a href="@Url.Action("DeleteOccupancy", new { id = item.occupancy_id})" title="Delete Occupancy"><span class="fa fa-trash"></span></a>


                    </td>
                </tr>
            }

        </table>


    </div> <!-- box body-->
        </div> <!-- box -->