Booking System/Controllers/AfterSalesController.cs
using Booking_System.Helpers;
using Booking_System.Models;
using Booking_System.Services;
using Booking_System.Services.Abstract;
using EntityFramework.Extensions;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Booking_System.Controllers
{
    [CustomAuthorize(UserRoles.Administrator, UserRoles.SuperAdministrator, UserRoles.Sales)]
    public class AfterSalesController : BaseController
    {
        private ABSDBEntities db = new ABSDBEntities();
        log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: AfterSales
        public ActionResult ViewAfterSales()
        {
            List<booking> allAfterSalesBookings = new List<booking>();

            //All completed bookings only
            var allBookings = db.bookings.Where(e=> e.status == 6);
            if (allBookings != null && allBookings.Count() > 0)
            {
                foreach (var bk in allBookings)
                {
                    if(IsValidBookingForAfterSales(bk))
                    {
                        allAfterSalesBookings.Add(bk);
                    }
                }
            }

            return View(allAfterSalesBookings);
        }

        // GET: Reservation/Details/5
        public ActionResult BookingDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var booking = db.bookings.Find(id);
            refurbishbooking(booking);

            if (booking == null || !IsValidBookingForAfterSales(booking))
            {
                return HttpNotFound();
            }
            return View(booking);
        }


        public ActionResult AddActivities(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var booking = db.bookings.Find(id);
            if (booking == null || !IsValidBookingForAfterSales(booking))
            {
                return HttpNotFound();
            }

            refurbishbooking(booking);

            var vBooking = db.viewBookings.Where(x => x.booking_ref == booking.booking_ref).FirstOrDefault();
            if (vBooking != null)
            {
                ViewBag.VBooking = vBooking;
            }

            ViewBag.BookingRef = booking.booking_ref;
            ViewBag.Booking = booking;

            IReservationService res = new ReservationService();
            List<viewActivity> vActivity = res.GetReservationActivities(id.Value, booking);

            return View(vActivity);

        }

        [HttpPost]
        public ActionResult AddActivities(int booking_id, int[] activity_id, int[] transfer_type, int[] child, int[] adult, int[] activity_pricing_id, double[] priceAdult, double[] priceChild)
        {
            try
            {

                IReservationService res = new ReservationService();
                res.SaveReservationActivities(booking_id, activity_id, transfer_type, child, adult, activity_pricing_id, true, priceAdult, priceChild);


                return RedirectToAction("BookingDetails", new { id = booking_id });

            }
            catch (Exception e)
            {

                throw;
            }
        }

        public ActionResult AddRental(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var booking = db.bookings.Find(id);

            if (booking == null || !IsValidBookingForAfterSales(booking))
            {
                return HttpNotFound();
            }

            refurbishbooking(booking);

            var vBooking = db.viewBookings.Where(x => x.booking_ref == booking.booking_ref).FirstOrDefault();
            if (vBooking != null)
            {
                ViewBag.VBooking = vBooking;
            }

            IReservationService res = new ReservationService();
            IList<vehicle> vehiclesToDisplay = res.GetReservationRentals(id.Value, booking);

            ViewBag.Booking = booking;

            return View(vehiclesToDisplay);
        }

        [HttpPost]
        public ActionResult AddRental(int booking_id, double[] price, int[] days, int[] vehicle_id, bool[] hasDriver)
        {
            try
            {
                IReservationService res = new ReservationService();
                var pricewithdriver = price;

                res.SaveReservationRentals(booking_id, price, pricewithdriver, days, vehicle_id, true, hasDriver);

                return RedirectToAction("BookingDetails", new { id = booking_id });

            }
            catch (Exception e)
            {

                throw;
            }

        }

        public ActionResult AddTransfer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var booking = db.bookings.Find(id);

            if (booking == null || !IsValidBookingForAfterSales(booking))
            {
                return HttpNotFound();
            }

            refurbishbooking(booking);

            IReservationService res = new ReservationService();
            IList<transferPricing> transfers = res.GetReservationTransfers(id.Value, booking);

            int currency_id = 0;
            market m = db.markets.Find(booking.market_id);
            if (m != null)
            {
                currency_id = m.currency_id;
            }


            var pricings = db.transferPricings.Where(x => x.currency_id == currency_id).ToList();

            ViewBag.TransferPricings = pricings;

            ViewBag.Booking = booking;

            return View(transfers);
        }

        //[HttpPost]
        //public ActionResult AddTransfer(int booking_id, int? transfer, int? coach, double? totalPriceTransfer, double? totalPriceCoach)
        //{
        //    try
        //    {

        //        IReservationService res = new ReservationService();
        //        res.SaveReservationTransfers(booking_id, transfer, totalPriceTransfer, totalPriceCoach, true);

        //        return RedirectToAction("BookingDetails", new { id = booking_id });

        //    }
        //    catch (Exception)
        //    {

        //        throw;
        //    }
        //}

        [HttpPost]
        public ActionResult AddTransfer(int booking_id, int? transfer, double? totalPriceTransfer)
        {
            try
            {

                IReservationService res = new ReservationService();
                res.SaveReservationTransfers(booking_id, transfer, totalPriceTransfer, null, true);

                return RedirectToAction("BookingDetails", new { id = booking_id });

            }
            catch (Exception)
            {

                throw;
            }
        }


        private bool IsValidBookingForAfterSales(booking bk)
        {
            bool result = false;
            var today = DateTime.Now.Date;
            if (bk != null)
            {
                if (bk.checkin_date.HasValue)
                {
                    if (bk.checkin_date.Value.Date <= today)
                    {
                        if(bk.checkout_date.HasValue)
                        {
                            if(bk.checkout_date.Value.Date < today)
                            {
                                return false;
                            }
                        }
                        return true;
                    }
                }
            }

            return result;
        }
    }
}

Booking System/Views/AfterSales/AddActivities.cshtml
@model IEnumerable<Booking_System.Models.viewActivity>
@using utils = Booking_System.Helpers.Utils
@{
    ViewBag.Title = "Activities";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.TreeView = "AS";

    var booking = ViewBag.Booking as Booking_System.Models.booking;
    var guests = booking._totalGuests;
    var minors = booking._totalChildrenAndTeens;
    var anyminor = minors > 0;

    var symbol = string.Empty;
    if (booking != null && booking.market != null && booking.market.currency != null)
    {
        symbol = booking.market.currency.symbol;
    }

}

<h2>Activities Details</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li><a href="@Url.Action("ViewAfterSales","AfterSales")">AfterSales</a></li>
    <li><a href="@Url.Action("BookingDetails","AfterSales", new {id = booking.booking_id })">@booking.booking_name</a></li>
    <li class="active">Add Activities</li>
</ol>

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Activities Details</h3>

    </div><!-- /.box-header -->
    <div class="box-body">

        @if (Model == null || Model.Count() == 0)
        {
            <h1><span class="fa fa-warning"></span> No Activities Available</h1>

        }
        else
        {


            <div class="row">
                <div class="col-md-8">

                    @using (Html.BeginForm("AddActivities", "AfterSales", FormMethod.Post))
                {
                        @Html.AntiForgeryToken()

                        <input type="hidden" name="booking_id" value="@booking.booking_id" />
                        <table class="table">

                            @{ string category = ""; int i = 0;}
                            @foreach (var activity in Model)
                            {


                                if (category != activity.category)
                                {
                                    <tr>
                                        <td colspan="6">
                                            <h4 class="booking-filters-title"><span class=""></span>&nbsp;@activity.category.ToUpper()</h4>
                                            @*<p class="readmore"><span class="large">@activity.activity_name</span> @activity.description</p>*@
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>activity</td>
                                        <td>Transfer (pp adult @(anyminor ? "/child" : ""))</td>
                                        <td>Adults</td>
                                        @if (anyminor)
                                        {
                                            <td>Children</td>
                                        }


                                    </tr>
                                }


                                <tr class="@(activity._isSelected ? "activity-selected" : "")">
                                    <th>
                                        @if (!activity._SoldInFrontEnd)
                                        {

                                            <input type="hidden" name="activity_id[@i]" value="@activity.activity_id" />
                                            <input type="hidden" name="activity_pricing_id[@i]" value="@activity.activity_pricing_id" />
                                        }

                                        @activity.activity_name <small>@(activity.min_age.HasValue && activity.min_age.Value > 0 ? String.Concat("(", activity.min_age.Value.ToString(), ")") : "")</small>
                                        @if (!activity._SoldInFrontEnd)
                                        {
                                            if ((activity.price_adult + activity.price_child > 0))
                                            {
                                                <br /><small>No Transfer - @activity.symbol @activity.price_adult / @activity.price_child </small>
                                            }
                                            if ((activity.price_adult_incl_sic_transfer + activity.price_child_incl_sic_transfer > 0))
                                            {

                                                <br /><small>Seat In Coach - @activity.symbol @activity.price_adult_incl_sic_transfer / @activity.price_child_incl_sic_transfer  </small>
                                            }
                                            if ((activity.price_adult_incl_private_transfer + activity.price_child_incl_private_transfer > 0))
                                            {

                                                <br /><small>Private - @activity.symbol @activity.price_adult_incl_private_transfer / @activity.price_child_incl_private_transfer</small>
                                            }
                                        }
                                    </th>
                                    <td>
                                        @if (activity._SoldInFrontEnd)
                                        {

                                            if ((activity.price_adult + activity.price_child > 0) && activity.transfer_type == 0)
                                            {
                                                <span>No Transfer - @activity.symbol @activity.price_adult / @activity.price_child </span>
                                            }
                                            if ((activity.price_adult_incl_sic_transfer + activity.price_child_incl_sic_transfer > 0) && activity.transfer_type == 1)
                                            {
                                                <span>Seat In Coach - @activity.symbol @activity.price_adult_incl_sic_transfer / @activity.price_child_incl_sic_transfer  </span>
                                            }
                                            if ((activity.price_adult_incl_private_transfer + activity.price_child_incl_private_transfer > 0) && activity.transfer_type == 2)
                                            {
                                                <span>Private - @activity.symbol @activity.price_adult_incl_private_transfer / @activity.price_child_incl_private_transfer</span>
                                            }
                                        }
                                        else
                                        {
                                            <input type="hidden" name="transfer_type[@i]" value="-1" />
                                            <div class="row">
                                                <div class="col-md-5">
                                                    <input type="number" name="priceAdult[@i]" value="@activity._final_price_adult" class="form-control" />
                                                </div>
                                                @if (anyminor)
                                                {
                                                    <div class="col-md-1">
                                                        /
                                                    </div>
                                                    <div class="col-md-5">
                                                        <input type="number" name="priceChild[@i]" value="@activity._final_price_child" class="form-control" />
                                                    </div>
                                                }
                                            </div>
                                        }
                                    </td>

                                    <td style="width:100px;">
                                        @if (activity._SoldInFrontEnd)
                                        {
                                            <span>@activity._adult</span>
                                        }
                                        else
                                        {
                                            <select name="adult[@i]" class="form-control">
                                                @for (int a = 0; a <= guests; a++)
                                                {
                                                    <option value="@a" @(activity._adult == a ? "selected=selected" : "")>@a</option>
                                                }
                                            </select>
                                        }

                                    </td>


                                    @if (anyminor)
                                    {
                                        <td style="width:100px;">
                                            @if (activity.min_age < 18 && activity.has_price_child && !activity._SoldInFrontEnd)
                                            {
                                                <select name="child[@i]" class="form-control">
                                                    @for (int c = 0; c <= minors; c++)
                                                    {
                                                        <option value="@c" @(activity._child == c ? "selected=selected" : "")>@c</option>

                                                    }
                                                </select>
                                            }
                                            else
                                            {
                                                if (!activity._SoldInFrontEnd)
                                                {
                                                    <input type="hidden" name="child[@i]" value="0" />
                                                }
                                                <span> - </span>
                                            }
                                        </td>
                                    }

                                </tr>






                                {
                                    category = activity.category;

                                    if (!activity._SoldInFrontEnd)
                                    {
                                        i++;
                                    }
                                }


                            }
                        </table>

                        <div style="clear:both"></div>
                        <div class="gap"></div>
                        <button type="submit" value="save" name="submitaction" class="btn btn-default">Save</button>
                        <div class="gap"></div>


                                }



                </div>



            </div>
                                }
    </div>
</div>

Booking System/Views/AfterSales/AddTransfer.cshtml
@model IEnumerable<Booking_System.Models.transferPricing>
@using utils = Booking_System.Helpers.Utils
@{
    ViewBag.Title = "Transfer";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.TreeView = "AS";
    //var vehicles = ViewBag.Vehicles as List<Booking_System.Models.vehicle>;

    var booking = ViewBag.Booking as Booking_System.Models.booking;

    var ccy = string.Empty;
    if (booking != null && booking.market != null && booking.market.currency != null)
    {
        ccy = booking.market.currency.symbol;
    }

    var pricings = ViewBag.TransferPricings as List<Booking_System.Models.transferPricing>;

    bool selected = false;

    if (Model != null)
    {
        selected = Model.Count(e => e._isSelected && !e._isAfterSales) > 0;
    }


}

<h2>Transfer Details</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li><a href="@Url.Action("ViewAfterSales","AfterSales")">AfterSales</a></li>
    <li><a href="@Url.Action("BookingDetails","AfterSales", new {id = booking.booking_id })">@booking.booking_name</a></li>
    <li class="active">Add Transfer</li>
</ol>

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Transfer Details</h3>

    </div><!-- /.box-header -->
    <div class="box-body">

        <div class="col-md-8">
            @if (Model == null || Model.Count() == 0 || pricings.Count() == 0 || selected)
            {
                <h1><span class="fa fa-warning"></span> No Transfers Available</h1>
            }
            else
            {
                double? price = 0D;

                using (Html.BeginForm("AddTransfer", "AfterSales", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" name="booking_id" value="@booking.booking_id" />
                    <input type="hidden" name="totalPriceTransfer" value="" />

                    <table class="table">
                        <tr>
                            <td align="center">
                                <label>
                                    <input class="i-radio" type="radio" checked name="transfer" value="0" />
                                </label>
                            </td>
                            <td>
                                no transfer
                            </td>
                            <td>
                                No transfer booked
                            </td>
                            <td>0</td>

                        </tr>
                        @if (pricings.Count > 0)
                        {
                            foreach (var item in Model.OrderBy(x => x.transfer_id))
                            {
                                    var rate = pricings.Where(x => x.transfer_id == item.transfer_id).FirstOrDefault();
                                    double? defaultPrice = (rate.adult_price * booking.adults) + (rate.child_price * booking.children) + (rate.teen_price * booking.teens);

                                    price = defaultPrice;
                                    if (item._totalPrice.HasValue)
                                    {
                                        price = item._totalPrice;
                                    }

                                <tr>
                                    <td align="right">
                                        <label>
                                            <input class="i-radio radioPriceTransfer" type="radio" @(item._isSelected ? "checked" : "") name="transfer" value="@item.transfer_id" />
                                        </label>
                                    </td>
                                    <td>
                                        @item.transfer.name
                                    </td>
                                    <td>
                                        @item.transfer.description <small>@ccy@defaultPrice</small>
                                    </td>
                                    <td>
                                        <input type="number" class="form-control small-item totalPriceTransfer @(item._isSelected? "totalPriceTransferChecked" : "" )" value="@price" />
                                       
                                    </td>

                                </tr>
                                                }
                                            }




                    </table>
                    <button type="submit" class="btn btn-default">Save</button>
                    <br />

                                            } <!-- form -->


                                            } <!-- endif -->




            <div class="gap"></div>
            @* end form *@

        </div>

    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $("[name='totalPriceTransfer']").val($('.totalPriceTransferChecked').val());

            $('body').on('keyup', '.totalPriceTransfer', function () {
                var radioButton = $(this).closest('tr').find('.i-radio');
                if (radioButton != null) {
                    if (radioButton[0].checked) {
                        $("[name='totalPriceTransfer']").val($(this).val());
                    }
                }

            });

            $('body').on('change', '.radioPriceTransfer', function () {
                if ($(this)[0].checked) {
                    var textBox = $(this).closest('tr').find('.totalPriceTransfer');
                    if (textBox != null) {
                        $("[name='totalPriceTransfer']").val(textBox.val());
                    }
                }
            });
        });
    </script>
}

Booking System/Views/AfterSales/ViewAfterSales.cshtml
@model IEnumerable<Booking_System.Models.booking>

@{
    ViewBag.Title = "View AfterSales";
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Menu = "List";
    ViewBag.TreeView = "AS";
}

<h2>View Bookings</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li class="active">AfterSales</li>
</ol>

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Booking List</h3>

    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">


        <table class="table table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.booking_id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.booking_date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.booking_file_number)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.booking_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.checkin_date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.checkout_date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.num_nights)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model._totalGuests)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalCostWithCurrency)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.discount_amt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.user1.FullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.statusDesc)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.booking_id)
                    </td>
                    <td>
                        @item.booking_date.Value.ToString("dd mm yyyy")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.booking_file_number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.booking_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.checkin_date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.checkout_date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.num_nights)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item._totalGuests)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalCostWithAfterSales)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.discount_amt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.user1.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.statusDesc)
                    </td>
                    <td>
                        <a href="@Url.Action("BookingDetails", new { id = item.booking_id})" title="view Boooking"><span class="fa fa-tv"></span></a>
                    </td>
                </tr>
            }

        </table>
    </div>  <!-- .box-body-->
</div> <!-- .box-->