Booking System/Models/ViewModel/VehicleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Booking_System.Models.ViewModel
{
    public class VehicleViewModel
    {


        public int? provider_id { get; set; }
        public int? currency_id { get; set; }

        public VehicleViewModel()
        {
            Vehicle = new vehicle();
            VehiclePricing = new vehiclePricing();
            VehiclePicture = new picture();
            VehiclePricings = new List<vehiclePricing>();
            //TransferPricing = new transferPricing();
            //TransferPricings = new List<transferPricing>();


        }

        public vehicle Vehicle { get; set; }
        public vehiclePricing VehiclePricing { get; set; }

        //public transferPricing TransferPricing { get; set; }

        public IList<vehiclePricing> VehiclePricings { get; set; }
        //public IList<transferPricing> TransferPricings { get; set; }

        public picture VehiclePicture { get; set; }
    }
}

Booking System/Models/contact.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int contact_id { get; set; }
        public Nullable<int> provider_id { get; set; }
        public string salutation { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string job_title { get; set; }
        public string office_phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string notes { get; set; }
        public bool is_active { get; set; }
    
        public virtual provider provider { get; set; }
    }
}

Booking System/Models/vehicle.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicle()
        {
            this.vehicle_feature = new HashSet<vehicleFeature>();
            this.vehicle_picture = new HashSet<vehiclePicture>();
            this.vehicle_pricing = new HashSet<vehiclePricing>();
            this.booking_rental = new HashSet<bookingRental>();
        }
    
        public int vehicle_id { get; set; }
        public int provider_id { get; set; }
        public string service_name { get; set; }
        public string vehicle_model { get; set; }
        public string vehicle_type { get; set; }
        public string service_description { get; set; }
        public Nullable<int> max_seat { get; set; }
        public bool is_active { get; set; }
        public bool is_transfer { get; set; }
        public bool includes_driver { get; set; }
        public Nullable<short> engine_size { get; set; }
        public Nullable<short> year { get; set; }
        public bool is_automatic { get; set; }
        public Nullable<byte> doors { get; set; }
        public Nullable<byte> fuel_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicleFeature> vehicle_feature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiclePicture> vehicle_picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiclePricing> vehicle_pricing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookingRental> booking_rental { get; set; }
        public virtual provider provider { get; set; }
    }
}

Booking System/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Booking_System.Models;
using Booking_System.Helpers;
using System.Data.Entity.Infrastructure;
using Booking_System.Models.ViewModel;
using EntityFramework.Extensions;

namespace Booking_System.Controllers
{
    public class VehiclesController : AdminController
    {
        private ABSDBEntities db = new ABSDBEntities();
        private Services.AdminService adminService = new Services.AdminService();

        //#region transfers

        //public ActionResult ListTransferProviders()
        //{
        //    var vehicles = db.transferPricings.Include(v => v.transfer);
        //    return View(vehicles.Where(x => x.is_active).ToList());
        //}



        //// GET: TestVehicle/Create
        //public ActionResult CreateTransferProvider()
        //{
        //    ViewBag.currency_id = new SelectList(db.currencies.Where(x => x.is_active), "currency_id", "code_desc");
        //    ViewBag.provider_id = new SelectList(db.providers.Where(x => x.provider_type == "R"), "provider_id", "name");

        //    return View();
        //}

        //// POST: TestVehicle/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        ////public ActionResult CreateVehicle([Bind(Include = @"vehicle_id,provider_id,service_name,vehicle_model,
        ////    vehicle_type,service_description,max_seat,is_active,is_transfer,includes_driver,engine_size,year,is_automatic,doors,fuel_type")] vehicle vehicle,
        ////    vehiclePricing vpricing, HttpPostedFileBase file, picture pic)

        //public ActionResult CreateTransferProvider(VehicleViewModel model, HttpPostedFileBase file)
        //{

        //    model.Vehicle.provider_id = model.provider_id.HasValue ? model.provider_id.Value : 0;
        //    model.TransferPricing.currency_id = model.currency_id.HasValue ? model.currency_id.Value : 0;
        //    model.Vehicle.vehicle_model = "Airport Transfer";
        //    if (ModelState.IsValid)
        //    {

        //        db.vehicles.Add(model.Vehicle);
        //        db.SaveChanges();

        //    }
        //    else {

        //        ViewBag.currency_id = new SelectList(db.currencies.Where(x => x.is_active), "currency_id", "code_desc");
        //        ViewBag.provider_id = new SelectList(db.providers.Where(x => x.provider_type == "R"), "provider_id", "name");

        //        return View();
        //    }


        //    //add errors for prices
        //    if (!model.TransferPricing.child_price.HasValue &&
        //        !model.TransferPricing.teen_price.HasValue &&
        //        !model.TransferPricing.adult_price.HasValue 
        //        )
        //    {
        //        ModelState.AddModelError("price_adult", "At least one price should be defined");
        //    }

        //    if (model.TransferPricing.currency_id == 0)
        //    {
        //        ModelState.AddModelError("currency_id", "Please select a currency");
        //    }

        //    //model.TransferPricing.vehicle_id = model.Vehicle.vehicle_id;


        //    db.transferPricings.Add(model.TransferPricing);
        //    db.SaveChanges();



        //    //3. save image
        //    //force the display order to -1
        //    model.VehiclePicture.display_order = -1;
        //    model.VehiclePicture.SectionId = model.Vehicle.vehicle_id;

        //    adminService.SaveResourceToDisk(file, model.VehiclePicture);


        //    return RedirectToAction("ListTransferProviders");
        //}

        //public ActionResult EditTransferProvider(int? id)
        //{
        //    try
        //    {

        //        if (id == null)
        //        {
        //            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //        }

        //        vehicle vehicle = db.vehicles.Find(id);
        //        if (vehicle == null)
        //        {
        //            return HttpNotFound();
        //        }

        //        ViewBag.provider_id = new SelectList(db.providers.Where(x => x.provider_type == "R"), "provider_id", "name");

        //        var currencies = db.currencies.Where(x => x.is_active).ToList();
        //        //var existCurrencies = db.transferPricings.Where(x => x.vehicle_id == id && x.is_active).Select(x => x.currency_id).ToList();
        //        //foreach (var ec in existCurrencies)
        //        //{
        //        //    var success = currencies.Remove(new currency { currency_id = ec });
        //        //}

        //        ViewBag.currency_id = new SelectList(currencies, "currency_id", "code_desc");

        //        return View(vehicle);
        //    }
        //    catch (Exception e)
        //    {
        //        throw;
        //    }
        //}


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult SaveTransferPricing([Bind(Include = "transfer_pricing_id,vehicle_id,currency_id,child_price,teen_price,adult_price")] transferPricing pricing)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        if (pricing.transfer_pricing_id > 0)
        //        {
        //            db.Entry(pricing).State = EntityState.Modified;
        //            db.SaveChanges();

        //        }
        //        else {

        //        pricing.is_active = true;
        //        db.transferPricings.Add(pricing);
        //        db.SaveChanges();
        //        //return RedirectToAction("EditVehicle", new { id = pricing.vehicle_id });
        //        }


        //    }

        //    var currencies = db.currencies.Where(x => x.is_active).ToList();
        //    //var existCurrencies = db.transferPricings.Where(x => x.vehicle_id == pricing.vehicle_id && x.is_active).Select(x => x.currency_id).ToList();
        //    //foreach (var ec in existCurrencies)
        //    //{
        //    //    currencies.Remove(new currency { currency_id = ec });
        //    //}

        //    ViewBag.currency_id = new SelectList(currencies, "currency_id", "code_desc");


        //    return RedirectToAction("EditTransfer", new { id = pricing.transfer_id });
        //}



        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult EditTransfer([Bind(Include = "vehicle_id,provider_id,service_name,vehicle_model,vehicle_type,service_description,max_seat,is_active,is_transfer,includes_driver")] vehicle vehicle)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(vehicle).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("ListTransfers");
        //    }
        //    ViewBag.provider_id = new SelectList(db.providers, "provider_id", "name", vehicle.provider_id);
        //    return View(vehicle);
        //}




        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult EditTransferPricing([Bind(Include = "transfer_pricing_id,vehicle_id,currency_id,child_price,teen_price,adult_price")] transferPricing transferpricing)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(transferpricing).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("ListTransfers");
        //    }
        //    //ViewBag.provider_id = new SelectList(db.providers, "provider_id", "name", vehicle.provider_id);
        //    return RedirectToAction("EditTransfer", new { id = transferpricing.transfer_id });
        //}



        //// GET: TestVehicle/Delete/5
        //public ActionResult DeleteTransferPricing(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }

        //    transferPricing transferPricing = db.transferPricings.Find(id);
        //    if (transferPricing == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    var transferId = transferPricing.transfer_id;
        //    db.transferPricings.Remove(transferPricing);
        //    db.SaveChanges();
        //    return RedirectToAction("EditTransfer", new { id = transferId });



        //}


        //// GET: TestVehicle/Delete/5
        //public ActionResult DeleteTransfer(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    vehicle vehicle = db.vehicles.Find(id);
        //    if (vehicle == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(vehicle);
        //}

        //// POST: TestVehicle/Delete/5
        //[HttpPost, ActionName("DeleteTransfer")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteTransferConfirmed(int id)
        //{
        //    vehicle vehicle = db.vehicles.Find(id);
        //    try
        //    {
        //        db.transferPricings.Where(x => x.transfer_id == id).Delete();

        //        db.vehicles.Remove(vehicle);
        //        db.SaveChanges();
        //        return RedirectToAction("ListTransfers");

        //    }
        //    catch (DbUpdateException ex)
        //    {
        //        db.Entry(vehicle).Reload();
        //        vehicle.is_active = false;
        //        db.Entry(vehicle).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("ListTransfers");

        //    }



        //}





        //#endregion

        #region new methods
        public ActionResult ListVehicles()

Booking System/Views/providers/Activities.cshtml
@model IEnumerable<Booking_System.Models.activity>

@{
    ViewBag.Title = "Activities";
    var providername = ViewBag.ProviderName;
}

<style>
    .box-header {
        background:#8CC440;
        color:#fff;
    }
</style>

<h2>Activities</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li><a href="@Url.Action("ActivityProviders","Providers")">Activity Providers</a></li>
    <li class="active">Activities</li>
</ol>


<div class="box">
    <div class="box-header">
        <h3 class="box-title">Activity List for <b>@providername</b></h3>
        <div class="box-tools">


            <a href="@Url.Action("Create","Activities")" class="btn btn-default pull-right"><span class="fa fa-plus-circle"></span> New Activity</a>
        </div>
    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
        <div class="box">

            <div class="box-body table-responsive no-padding">

                <table class="table table-hover">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.activity_name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.category)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.duration)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.provider.name)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.activity_name)
                            </td>
                            <td>
                                @Html.Raw(item.description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.category)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.duration)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.provider.name)
                            </td>

                            <td align="right">



                                <a href="@Url.Action("Details", "Activities", new { id = item.activity_id})" title="View Activity"><span class="fa fa-tv"></span></a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                                <a href="@Url.Action("Edit", "Activities", new { id = item.activity_id})" title="Edit Activity"><span class="fa fa-pencil"></span></a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                                <a href="@Url.Action("Delete", "Activities", new { id = item.activity_id})" title="Delete Activity"><span class="fa fa-trash"></span></a>

                            </td>

                        </tr>
                    }

                </table>

            </div>
        </div>
    </div>
</div>

Booking System/Views/providers/ContactDetails.cshtml
@model Booking_System.Models.contact
@using hotelTab = Booking_System.Helpers.AppEnums.HotelTab
@using provTab = Booking_System.Helpers.AppEnums.ProviderTab

@{
    ViewBag.Title = "Details";
    var hotelid = Model.provider_id;

    var _id = Model.provider.IsHotel ? hotelid : Model.provider.provider_id;
    var _controller = Model.provider.IsHotel ? "Hotels" : "Providers";
    var _provider = Model.provider.IsHotel ? "Hotel" : (Model.provider.IsRental ? "Car Rental" : (Model.provider.IsTourOperator ? "Tour Operator" : ""));
    var _methodList = Model.provider.IsHotel ? "ListHotels" : (Model.provider.IsRental ? "ListCarRentals" : (Model.provider.IsTourOperator ? "ListTourOperators" : ""));
    var _tab = Model.provider.IsHotel ? (int)hotelTab.CONTACTS : (Model.provider.IsRental ? (int)provTab.VEHICLES : (Model.provider.IsTourOperator ? (int)provTab.ACTIVITIES : (int)provTab.TRANSFER));
    var _methodDetails = Model.provider.IsHotel ? "HotelDetails" : "ProviderDetails";


}

<h2>Contact Details</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    
        <li><a href="@Url.Action(_methodList,_controller)">@_provider</a></li>
        <li><a href="@Url.Action(_methodDetails,_controller,new { id = _id, tab = _tab})">@Model.provider.name</a></li>
    
    <li class="active">@Model.TitleFullName</li>
</ol>

<div class="row">
    <div class="col-md-4">
        <!-- Widget: user widget style 1 -->
        <div class="box box-widget widget-user-2">
            <!-- Add the bg color to the header using any of the bg-* classes -->
            <div class="widget-user-header bg-gray">
                
                <h3 class="widget-user-username">@Model.firstname @Model.lastname</h3>
                <h5 class="widget-user-desc">@Model.job_title</h5>
                <h4 class="widget-user-desc">@Model.provider.name</h4>
            </div>
            <div class="box-body no-padding">
                <table class="table">
                    <tr>
                        <th style="width:30%">
                            <span class="fa fa-user"></span>&nbsp;name
                        </th>
                        <td>
                            @Html.DisplayFor(model => model.TitleFullName)
                        </td>
                    </tr><tr>
    <th>
        <span class="fa fa-mobile-phone"></span>&nbsp;mobile
    </th>
    <td>
        @Html.DisplayFor(model => model.mobile)
    </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="fa fa-phone"></span>&nbsp;office </th>
                        <td>
                            @Html.DisplayFor(model => model.office_phone)
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="fa fa-envelope"></span>&nbsp;email
                        </th>
                        <td>
                            @Html.DisplayFor(model => model.email)
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="fa fa-comment"></span>&nbsp;notes
                        </th>
                        <td>
                            @Html.Raw(Model.notes)
                        </td>


                    </tr>
                    <tr>
                        <td colspan="2" class="text-center">
                            <a href="@Url.Action(_methodDetails, _controller, new { id = _id, tab = _tab   })" class="btn btn-default">Back</a>                            
                        </td>
                    </tr>

                </table>
           
            </div>
        </div><!-- /.widget-user -->
    
        
          
            

        
    
    </div><!-- /.col -->
</div>



@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.contact_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

Booking System/Views/providers/ListCarRentals.cshtml
@model IEnumerable<Booking_System.Models.provider>

@{
    ViewBag.Title = "Car Rental Providers";
    ViewBag.TreeView = "R";
    ViewBag.Menu = "ListProviders";

}
<h2>Car Rental Providers</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li class="active">Car Rental Providers</li>
</ol>

<style>
    .celloverflow {
        max-width: 100px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
</style>

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Car Rental List</h3>
        <div class="box-tools">


            <a href="@Url.Action("CreateProvider","Providers", new { type="R"})" class="btn btn-default pull-right"><span class="fa fa-plus"></span> New Car Rental</a>
        </div>
    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
        <div class="box">

            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.name)
                        </th>
                        <th style="width:25%">
                            @Html.DisplayNameFor(model => model.description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.location)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.country)
                        </th>

                        <th></th>
                    </tr>

                    @foreach (var item in Model)
            {
                        <tr>
                            <td>
                                @*<a href="@Url.Action("Index","Vehicles", new { id = item.provider_id })">@item.name</a>*@
                                @item.name

                            </td>
                            <td class="celloverflow" title="@item.description">
                                @Html.Raw(item.description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.location)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.country)
                            </td>


                            <td align="right">


                                @*<a href="@Url.Action("Index","Vehicles", new { id = item.provider_id})" title="View Car Rental"><span class="ion ion-android-boat"></span></a>*@
                                <a href="@Url.Action("ProviderDetails", new { id = item.provider_id})" title="View Car Rental"><span class="fa fa-tv"></span></a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                                @*<a href="@Url.Action("EditProvider", new { id = item.provider_id})" title="Edit Car Rental"><span class="fa fa-pencil"></span></a>*@
                                <a href="@Url.Action("DeleteProvider", new { id = item.provider_id})" title="Delete Car Rental"><span class="fa fa-trash"></span></a>

                            </td>

                        </tr>
                    }

                </table>

            </div>
        </div>
    </div> <!-- box body-->
</div> <!-- box -->

Booking System/Views/providers/Vehicles.cshtml
@model IEnumerable<Booking_System.Models.vehicle>

@{
    ViewBag.Title = "Vehicules";
    var providername = ViewBag.ProviderName;
}


<style>
    .box-header {
        background: #8CC440;
        color: #fff;
    }
</style>

<h2>Vehicles</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li><a href="@Url.Action("CarRentalProviders","Providers")">Car Rental Providers</a></li>
    <li class="active">Activities</li>
</ol>

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Vehicle List for <b>@providername</b></h3>
        <div class="box-tools">


            <a href="@Url.Action("Create","Vehicles")" class="btn btn-default pull-right"><span class="fa fa-plus-circle"></span> New Activity</a>
        </div>
    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
        <div class="box">

            <div class="box-body table-responsive no-padding">

                <table class="table table-hover">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.service_name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.vehicle_model)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.vehicle_type)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.service_description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.min_seat)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.max_seat)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.includes_driver)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.is_active)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.is_transfer)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.provider.name)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.service_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.vehicle_model)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.vehicle_type)
                            </td>
                            <td>
                                @Html.Raw(item.service_description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.min_seat)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.max_seat)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.includes_driver)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.is_active)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.is_transfer)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.provider.name)
                            </td>
                            <td>
                                <a href="@Url.Action("Details", "Activities", new { id = item.vehicle_id})" title="View Vehicle"><span class="fa fa-tv"></span></a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                                <a href="@Url.Action("Edit", "Activities", new { id = item.vehicle_id})" title="Edit Vehicle"><span class="fa fa-pencil"></span></a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                                <a href="@Url.Action("Delete", "Activities", new { id = item.vehicle_id})" title="Delete Vehicle"><span class="fa fa-trash"></span></a
                            </td>
                        </tr>
                    }

                </table>

            </div>
        </div>
    </div>
</div