Booking System/Models/ViewModel/SalesReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Booking_System.Models.ViewModel
{
    public class SalesReport
    {
        public string   ProviderName                            {get;set;}
        public DateTime CheckinDate                             {get;set;}
        public DateTime checkout_date                           {get;set;}     
        public int      Adults                                  {get;set;}
        public int      TotalChildrenAndTeens                   {get;set;}             
        public int      bookingRoomCount                        {get;set;}        
        public int      NumNights                               {get;set;} 
        public string   currencyCode                            {get;set;}
        public double   TotalCostRooms                          {get;set;}
        public double   TotalCostSupps                          {get;set;}
        public string   isPackage                               {get;set;}
        public string   TransferType                            {get;set;}    
        public double   TotalCostTransferWithAfterSales         {get;set;}                       
        public double   TotalCostActivityWithAfterSales         {get;set;}                       
        public double   TotalCostRentalWithAfterSales           {get;set;}                     
        public double   TotalCost                               {get;set;}

    }
}

Booking System/Models/rateSheet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rateSheet
    {
        public string price_type { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int package_id { get; set; }
        public string package_name { get; set; }
        public int room_id { get; set; }
        public string room_name { get; set; }
        public int provider_id { get; set; }
        public string provider_name { get; set; }
        public int base_price_id { get; set; }
        public string description { get; set; }
        public int market_id { get; set; }
        public string currency_code { get; set; }
        public int currency_id { get; set; }
        public string symbol { get; set; }
        public Nullable<double> price_single { get; set; }
        public Nullable<double> price_twin { get; set; }
        public Nullable<double> price_triple { get; set; }
        public Nullable<double> price_quadruple { get; set; }
        public Nullable<double> price_honeymoon { get; set; }
        public Nullable<double> price_infant { get; set; }
        public Nullable<double> price_child { get; set; }
        public Nullable<double> price_teen { get; set; }
        public Nullable<double> price_ground_handling_adult { get; set; }
        public Nullable<double> price_ground_handling_teen { get; set; }
        public Nullable<double> price_ground_handling_child { get; set; }
        public Nullable<double> chg_infant { get; set; }
        public Nullable<double> chg_child { get; set; }
        public Nullable<double> chg_teen { get; set; }
        public Nullable<double> chg_adult { get; set; }
        public int incl_grnd_handling { get; set; }
        public int is_active { get; set; }
        public string contracted_offer { get; set; }
        public Nullable<int> number_nights { get; set; }
    }
}

Booking System/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Booking_System.Models;
using OfficeOpenXml;
using Booking_System.Models.ViewModel;
using static Booking_System.Helpers.AppEnums;

namespace Booking_System.Controllers
{
    public class ReportsController : BaseController
    {
        private ABSDBEntities db = new ABSDBEntities();



      
        public ActionResult Arrivals()
        {
            try
            {
                //DateTime start = startdate.HasValue ? startdate.Value : DateTime.Now;
                //DateTime end = enddate.HasValue ? enddate.Value : DateTime.Now.AddDays(7);
                ViewBag.Range = "";
                //var book = db.bookings.Where(x => x.checkin_date >= start && x.checkin_date <= end);
                var book = new List<booking>();
                return View(book);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public ActionResult Arrivals(DateTime? startdate, DateTime? enddate)
        {
            try
            {
                DateTime start = startdate.HasValue ? startdate.Value : DateTime.Now;
                DateTime end = enddate.HasValue ? enddate.Value : DateTime.Now.AddDays(7);
                ViewBag.start = start;
                ViewBag.end = end;
                ViewBag.Range = String.Concat(" from ", start.ToString("dd-MM-yyyy"), " to ", end.ToString("dd-MM-yyyy"));
                var book = db.bookings.Where(x => x.checkin_date >= start && x.checkin_date <= end  && x.status == (int)BookingStatus.COMPLETED);
                return View(book);
            }
            catch (Exception)
            {

                throw;
            }
        }

        
        public FileResult ArrivalsExport(DateTime? startdate, DateTime? enddate)
        {
            try
            {
                DateTime start = startdate.HasValue ? startdate.Value : DateTime.Now;
                DateTime end = enddate.HasValue ? enddate.Value : DateTime.Now.AddDays(7);
                ViewBag.start = start;
                ViewBag.end = end;
                ViewBag.Range = String.Concat(" from ", start.ToString("dd-MM-yyyy"), " to ", end.ToString("dd-MM-yyyy"));
                var book = db.bookings.Where(x => x.checkin_date >= start && x.checkin_date <= end && x.status == (int)BookingStatus.COMPLETED);
                List<ArrivalDeparture> lst = new List<ArrivalDeparture>();
                foreach(var bk in book)
                {
                    ArrivalDeparture ad = new ArrivalDeparture();
                    ad.BookingFilenumber = bk.booking_file_number;                                
                    ad.BookingName = bk.booking_name;
                    ad.AgentName = bk.agent_name;                   
                    ad.HotelName = bk.provider_name;
                    ad.Market = bk.market_name;
                    ad.CheckinDate = bk.checkin_date.HasValue? bk.checkin_date.Value.ToString("dd-MM-yyyy"):"";
                    ad.CheckoutDate = bk.checkout_date.HasValue ? bk.checkout_date.Value.ToString("dd-MM-yyyy") : "";
                    ad.Pax = bk.booking_guest.Count();
                    ad.EventDate = (bk.booking_guest.Min(x => x.arrival_datetime).HasValue ? bk.booking_guest.Min(x => x.arrival_datetime).Value.ToString("dd-MM-yyyy") : "N/A");
                    ad.EventTime = (bk.booking_guest.Min(x => x.arrival_datetime).HasValue ? bk.booking_guest.Min(x => x.arrival_datetime).Value.ToString("HH:mm") : "N/A");
                    lst.Add(ad);
                }

                using (ExcelPackage package = new ExcelPackage())
                {
                    var ws = package.Workbook.Worksheets.Add("Arrivals");
                    //true generates headers
                    ws.Cells["A1"].Value = "Booking File Number";
                    
                    ws.Cells["B1"].Value = "Booking Name";
                    ws.Cells["C1"].Value = "Agent Name";
                    ws.Cells["D1"].Value = "Hotel Name ";
                    ws.Cells["E1"].Value = "Market Name ";
                    ws.Cells["F1"].Value = "Check-in Date";
                    ws.Cells["G1"].Value = "Check-out Date ";
                    ws.Cells["H1"].Value = "No of pax";
                    ws.Cells["I1"].Value = "Arrival Date";
                    ws.Cells["J1"].Value = "Arrival Time";
                    ws.Cells["A2"].LoadFromCollection(lst);

                    int totalRows = ws.Dimension.End.Row;
                    int totalCols = ws.Dimension.End.Column;
                    var headerCells = ws.Cells[1, 1, 1, totalCols];
                    var headerFont = headerCells.Style.Font;
                    headerFont.Bold = true;
                    //headerFont.Italic = true;
                    ws.Cells.AutoFitColumns();

                    var stream = new System.IO.MemoryStream();
                    package.SaveAs(stream);

                    //string fileName = "Arrivals.xls+x";
                    string fileName = string.Format("Arrivals {0}-{1}.xlsx", start.ToString("ddMMMyyyy"), end.ToString("ddMMMyyyy"));
                
                    string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

                    stream.Position = 0;
                    return File(stream, contentType, fileName);
                }
            }
            catch (Exception)
            {

                throw;
            }
        }


        public ActionResult Departures()
        {
            try
            {
                //DateTime start = startdate.HasValue ? startdate.Value : DateTime.Now;
                //DateTime end = enddate.HasValue ? enddate.Value : DateTime.Now.AddDays(7);
                ViewBag.Range = "";
                //var book = db.bookings.Where(x => x.checkin_date >= start && x.checkin_date <= end);
                var book = new List<booking>();
                return View(book);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public ActionResult Departures(DateTime? startdate, DateTime? enddate)
        {
            try
            {
                DateTime start = startdate.HasValue ? startdate.Value : DateTime.Now;
                DateTime end = enddate.HasValue ? enddate.Value : DateTime.Now.AddDays(7);
                ViewBag.start = start;
                ViewBag.end = end;
                ViewBag.Range = String.Concat(" from ", start.ToString("dd-MM-yyyy"), " to ", end.ToString("dd-MM-yyyy"));
                var book = db.bookings.Where(x => x.checkout_date >= start && x.checkout_date <= end && x.status == (int)BookingStatus.COMPLETED);
                return View(book);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public FileResult DeparturesExport(DateTime? startdate, DateTime? enddate)
        {
            try
            {
                DateTime start = startdate.HasValue ? startdate.Value : DateTime.Now;
                DateTime end = enddate.HasValue ? enddate.Value : DateTime.Now.AddDays(7);
                ViewBag.start = start;
                ViewBag.end = end;
                ViewBag.Range = String.Concat(" from ", start.ToString("dd-MM-yyyy"), " to ", end.ToString("dd-MM-yyyy"));
                var book = db.bookings.Where(x => x.checkout_date >= start && x.checkout_date <= end && x.status == (int)BookingStatus.COMPLETED);
                List<ArrivalDeparture> lst = new List<ArrivalDeparture>();
                foreach (var bk in book)
                {
                    ArrivalDeparture ad = new ArrivalDeparture();
                    ad.BookingFilenumber = bk.booking_file_number;
                    ad.BookingName = bk.booking_name;
                    ad.AgentName = bk.agent_name;
                    ad.HotelName = bk.provider_name;
                    ad.Market = bk.market_name;
                    ad.CheckinDate = bk.checkin_date.HasValue ? bk.checkin_date.Value.ToString("dd-MM-yyyy") : "";
                    ad.CheckoutDate = bk.checkout_date.HasValue ? bk.checkout_date.Value.ToString("dd-MM-yyyy") : "";
                    ad.Pax = bk.booking_guest.Count();
                    ad.EventDate = (bk.booking_guest.Min(x => x.departure_datetime).HasValue ? bk.booking_guest.Min(x => x.departure_datetime).Value.ToString("dd-MM-yyyy") : "N/A");
                    ad.EventTime = (bk.booking_guest.Min(x => x.departure_datetime).HasValue ? bk.booking_guest.Min(x => x.departure_datetime).Value.ToString("HH:mm") : "N/A");
                    lst.Add(ad);
                }

                using (ExcelPackage package = new ExcelPackage())
                {
                    var ws = package.Workbook.Worksheets.Add("Departures");
                    //true generates headers
                    ws.Cells["A1"].Value = "Booking File Number";
                    ws.Cells["B1"].Value = "Booking Name";
                    ws.Cells["C1"].Value = "Agent Name";
                    ws.Cells["D1"].Value = "Hotel Name ";
                    ws.Cells["E1"].Value = "Market Name ";
                    ws.Cells["F1"].Value = "Check-in Date";
                    ws.Cells["G1"].Value = "Check-out Date ";
                    ws.Cells["H1"].Value = "No of pax";
                    ws.Cells["I1"].Value = "Departure Date";
                    ws.Cells["J1"].Value = "Departure Time";
                    ws.Cells["A2"].LoadFromCollection(lst);


                    int totalRows = ws.Dimension.End.Row;
                    int totalCols = ws.Dimension.End.Column;
                    var headerCells = ws.Cells[1, 1, 1, totalCols];
                    var headerFont = headerCells.Style.Font;

Booking System/Views/Reports/Arrivals.cshtml
@model IEnumerable<Booking_System.Models.booking>


@{
    ViewBag.Title = "Arrivals";
    ViewBag.TreeView = "R";
    ViewBag.Menu = "ARR";
    var range = ViewBag.Range;
    DateTime noDate = new DateTime(1900, 1, 1);
    }



<h2>Arrivals @range</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li class="active">Arrivals</li>
</ol>
<a href="#" class="showSection"><span class="fa fa-search-plus"></span> search</a>
<section style="display: @(Model.Count() >0?"none":"block")">


    <div class="box">
        <div class="box-header box-danger ">
            <div class="row">
                <div class="col-md-11"><h3 class="box-title">Search </h3></div>
                <div class="col-md-1 text-right closesearch"><a href="#"><span class="text-muted fa fa-close"></span></a></div>
            </div>
        </div><!-- /.box-header -->
        <div class="box-body">

            @using (Html.BeginForm())
            {
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="startdate" class="control-label ">Check-in Date</label>
                            <input type="text" class="form-control datepickerdown" required name="startdate" value="@ViewBag.start" />
                        </div>
                    </div>

                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="enddate" class="control-label ">Check-out Date</label>
                            <input type="text" class="form-control datepickerdown" required name="enddate" value="@ViewBag.end" />
                        </div>
                    </div>

                    <div class="col-md-1">
                        <div class="form-group">
                            <label class="control-label"></label>
                            <input type="submit" value="Search" class="form-control btn btn-default" />
                        </div>

                    </div>
                </div>

            }

        </div> <!-- box body-->
    </div> <!-- box -->
    </section>
    @if (Model.Count() > 0)
    {
        <div class="box">
            <div class="box-header box-danger ">
                <h3 class="box-title">
                    @*<a href="#" id="btnExportToExcel" class="btn btn-default">Export to excel</a>*@
                    <a href="@Url.Action("ArrivalsExport","Reports",new { @startdate = ViewBag.start, @enddate = ViewBag.end })" id="btnExportExcel" class="btn btn-default">Export to Excel </a>
                </h3>
            </div><!-- /.box-header -->
            <div class="box-body table-responsive no-padding">

                <table class="table" id="plannedarrival" data-tableName="Planned Arrivals">
                    <thead>
                        <tr>
                            <th>
                                Booking File Number
                            </th>
                            <th>
                                Booking Name
                            </th>
                            <th>
                                Agent Name
                            </th>
                            <th>
                                Hotel
                            </th>
                            <th>
                                Market
                            </th>
                            <th>
                                Check-in Date
                            </th>
                            <th>
                                Check-out Date
                            </th>
                            <th>
                                No of Pax
                            </th>
                            <th>
                                Arrival Date
                            </th>
                            <th>
                                Arrival Time
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.booking_file_number)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.booking_name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.agent_name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.provider_name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.market_name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.checkin_date)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.checkout_date)
                                </td>
                                <td>
                                    @item.booking_guest.Count()
                                </td>
                                <td>
                                    @{DateTime dt = item.booking_guest.Min(x => x.arrival_datetime).HasValue ? item.booking_guest.Min(x => x.arrival_datetime).Value : noDate; }
                                    @(dt == noDate ? "N/A" : dt.ToString("dd-MM-yyyy"))
                                </td>
                                <td>
                                    @(dt == noDate ? "N/A" : dt.ToString("HH:mm"))
                                </td>


                            </tr>
                                        }
                    </tbody>
                </table>

            </div> <!-- box body-->
        </div> <!-- box -->
                                        }


    @section Scripts {
        @Scripts.Render("~/bundles/table2excel")
        <script>

     
        $(document).ready(function () {
            $('.showSection').click(function () {
                $(this).next('section').show();

            });

            $('.closesearch').click(function () {
                $(this).closest('section').hide();
            });
        });


        </script>
    }

Booking System/Views/Reports/Departures.cshtml
@model IEnumerable<Booking_System.Models.booking>


@{
    ViewBag.Title = "Departures";
    ViewBag.TreeView = "R";
    ViewBag.Menu = "DEP";
    var range = ViewBag.Range;
    DateTime noDate = new DateTime(1900, 1, 1);

}



<h2>Departures @range</h2>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Menu","Home")">Menu</a></li>
    <li class="active">Departures</li>
</ol>
    <a href="#" class="showSection"><span class="fa fa-search-plus"></span> search</a>
    <section style="display: @(Model.Count() >0?"none":"block")">
<div class="box">
    <div class="box-header box-danger ">
    <div class="row">
        <div class="col-md-11"><h3 class="box-title">Search </h3></div>
        <div class="col-md-1 text-right closesearch"><a href="#"><span class="text-muted fa fa-close"></span></a></div>
    </div>
        
    </div><!-- /.box-header -->
    
    <div class="box-body">

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-5">
            <div class="form-group">
                <label for="startdate" class="control-label ">Check-in Date</label>
                <input type="text" class="form-control datepickerdown" required name="startdate" value="@ViewBag.start" />
            </div>
        </div>

        <div class="col-md-5">
            <div class="form-group">
                <label for="enddate" class="control-label ">Check-out Date</label>
                <input type="text" class="form-control datepickerdown" required name="enddate" value="@ViewBag.end" />
            </div>
        </div>

        <div class="col-md-1">
            <div class="form-group">
                <label class="control-label"></label>
                <input type="submit" value="Search" class="form-control btn btn-default" />
            </div>

        </div>
    </div>

}

    </div> <!-- box body-->

</div> <!-- box -->
    </section>
@if (Model.Count() > 0)
{
<div class="box">
    <div class="box-header box-danger ">
        <h3 class="box-title">
            @*<a href="#" id="btnExportToExcel" class="btn btn-default">Export to excel</a>*@
            <a href="@Url.Action("DeparturesExport","Reports",new { startdate = ViewBag.Start, enddate = ViewBag.end })" id="btnExportExcel" class="btn btn-default">Export to Excel </a>
        </h3>
    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">

            <table class="table" id="departures" data-tableName="Departures">
                <thead>
                    <tr>
                        <th>
                            Booking File Number
                        </th>
                        <th>
                            Booking Name
                        </th>
                        <th>
                            Agent Name
                        </th>
                        <th>
                            Hotel
                        </th>
                        <th>
                            Market
                        </th>
                        <th>
                            Check-in Date
                        </th>
                        <th>
                            Check-out Date
                        </th>
                        <th>
                            No of Pax
                        </th>
                        <th>Departure Date</th>
                        <th>Departure Time</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.booking_file_number)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.booking_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.agent_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.provider_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.market_name)
                            </td>                          
                            <td>
                                @Html.DisplayFor(modelItem => item.checkin_date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.checkout_date)
                            </td>
                            <td>
                                @item.booking_guest.Count()
                            </td>
                            <td>
                                @{DateTime dt = item.booking_guest.Min(x => x.departure_datetime).HasValue ? item.booking_guest.Min(x => x.departure_datetime).Value : noDate; }
                                @(dt == noDate ? "N/A" : dt.ToString("dd-MM-yyyy"))
                            </td>
                            <td>
                                @(dt == noDate ? "N/A" : dt.ToString("HH:mm"))
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
       
    </div> <!-- box body-->
</div> <!-- box -->
}


@section Scripts {
@Scripts.Render("~/bundles/table2excel")
    <script>

       
        $(document).ready(function () {
            $('.showSection').click(function () {
                $(this).next('section').show();

            });

            $('.closesearch').click(function () {
                $(this).closest('section').hide();
            });
        });

    </script>
}